### ISSUE TITLE
book

### ISSUE THREAD

**Issue by brunooomelo** [lucasfcosta/testing-javascript-applications#1]
do you have the book link?

**Comment by lucasfcosta** [comment]
Hi Bruno,

The book is not yet available, but it will be soon. I’ll make sure to post a link here as soon as it’s on sale.

Thanks for your interest!

**Comment by brunooomelo** [comment]
do you have any book preview or release date?

**Comment by lucasfcosta** [comment]
It should be available on Manning's Early Access Program very soon. I don't have any exact dates yet, but I believe that should be approximately in a month from now.

**Comment by lucasfcosta** [comment]
Hi @brunooomelo, the book is now available for earl access at https://www.manning.com/books/testing-javascript-applications.

Until the 28th of May, you can use the code `mldacosta` for a 50% discount 😄
