### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kubik-a** [lucasfcosta/testing-javascript-applications#22]
https://github.com/lucasfcosta/testing-javascript-applications/blob/e7a9a460827c522d0539607c5df23ae8bb5d788c/chapter4/1_setting_up_a_test_environment/1_exposing_modules/3_unit_tests/cartController.test.js#L71

Test Should be :

test('returns false for cards with more than 3 items of a kind',....)

**Comment by lucasfcosta** [comment]
Hi @Kubik-a, thank you for the issue! Would you like to open a PR to update the test description? If so, that would be welcome. Otherwise, I will fix this next week to give you time to create the PR yourself.
